### ISSUE TITLE
建议可以修改屏幕大小

### ISSUE THREAD

**Issue by squid233** [QWERTY770/Minecraft-2D-Python#4]
还是那个老问题，游戏屏幕太大了

**Comment by squid233** [comment]
经过调查，在31行处可以修改屏幕大小

**Comment by QWERTY770** [comment]
经过调查，在31行处修改屏幕大小不是一个好办法，因为42,43,49行都是硬编码的位置（1074，562，238都是计算出来的）

改屏幕大小后游戏就乱了
